export const data = {
  title: "Blog Post/Article Title Goes Here",
  date: "08 June 2022",
  subtitle:
    "Short synopsis of the post to tease reader to read more. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pulvinar sed congue viverra volutpat ridiculus amet. Congue eget diam velit ornare dictum.",
  body: [
    "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Imperdiet nullam eu sapien velit morbi sapien nisi. Cursus ornare rhoncus sollicitudin urna dolor felis, consectetur. Aliquam, nulla neque id curabitur. Quis vitae commodo, ultrices eros posuere felis sagittis. Donec cursus pellentesque pellentesque felis cursus tincidunt non. Scelerisque libero orci, turpis eget lorem id turpis lorem. Enim molestie tellus massa quam magnis congue. Nibh eu tristique orci neque, mauris. Eget bibendum imperdiet cursus nulla pulvinar. Lectus morbi enim vitae nisl netus in. Sed leo aliquam augue augue dignissim rhoncus. Ac, lobortis penatibus elementum turpis varius. Ante ultrices risus quis etiam tortor commodo eu nunc.</p> <p>Nisl, tristique tincidunt cursus ultrices quisque nullam aenean sit amet. Rhoncus posuere vivamus eget nunc. Nullam enim molestie aliquam iaculis. Vitae sed egestas tortor semper vehicula sed. Diam, convallis placerat elit commodo. Laoreet sed habitant nunc adipiscing amet, scelerisque mi quisque. Ante maecenas orci, varius suscipit est vitae, amet. Vitae id lacus mi hac id pellentesque sit turpis.</p> <p>Platea in cras pharetra posuere sollicitudin ultrices erat sagittis vel. Convallis vitae dictum nec senectus faucibus quis. Lectus faciÍlisis lobortis sollicitudin amet arcu ultrices. Facilisis fermentum quis mauris amet cum non semper. Vulputate tristique vitae pharetra ultrices nec pulvinar eget dolor, egestas. Placerat morbi aenean ut mi blandit. Diam.</p>",
    "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Amet, dignissim dignissim orci massa nunc, faucibus aliquam. Etiam mattis volutpat lorem urna adipiscing vitae velit eget. Turpis amet nec nisl vel diam malesuada dictum tincidunt amet. Egestas etiam enim justo, lorem leo etiam.</p> <p>Bibendum suspendisse ipsum donec vestibulum sed pellentesque lectus. Rhoncus purus, sed at lectus. Erat id porttitor pulvinar tristique. In sed sed volutpat dignissim porttitor a. Amet a tincidunt blandit vulputate sed. Viverra.</p>",
  ],
};
